# Numpy_Assignment_2::

In [ ]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:

arr = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
arr = arr.reshape((2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [15]:

arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.ones((2,5))
arr3 = np.vstack((arr1,arr2))
arr3 = arr3.astype('int32')
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:

arr4 = np.hstack((arr1,arr2))
arr4 = arr4.astype('int32')
print(arr4)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:

arr = arr.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:

  arr5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
arr5 = np.ravel(arr5)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [18]:
arr5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [19]:
arr6 = np.random.randint(1,25, size = (5,5))
print("Original Array: \n")
print (arr6)
print("\n")
print("Square of Array: \n")
print(arr6 ** 2)

Original Array: 

[[ 4  4 20  3  7]
 [ 8  9 24  3  3]
 [24 14 12 21 10]
 [ 4  1 11 24  9]
 [23 19  2 19  2]]


Square of Array: 

[[ 16  16 400   9  49]
 [ 64  81 576   9   9]
 [576 196 144 441 100]
 [ 16   1 121 576  81]
 [529 361   4 361   4]]


## Question:8

### Create 5x6 an array and find the mean?

In [20]:

arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Mean of Array: \n")
print(arr8.mean())

Original Array: 

[[16 13  1  1 14 16]
 [ 1  2 19 16 13 18]
 [ 1 16 19 16 14  4]
 [ 3  9  4 10  8 17]
 [ 8 17  6  2  7  5]]


Mean of Array: 

9.866666666666667


## Question:9

### Find the standard deviation of the previous array in Q8?

In [21]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(arr8))

Original Array: 

[[16 13  1  1 14 16]
 [ 1  2 19 16 13 18]
 [ 1 16 19 16 14  4]
 [ 3  9  4 10  8 17]
 [ 8 17  6  2  7  5]]


Standard deviation of Array: 

6.286139956726668


## Question:10

### Find the median of the previous array in Q8?

In [22]:

print("Original Array: \n")
print (arr8)
print("\n")
print("Median of Array: \n")
print(np.median(arr8))

Original Array: 

[[16 13  1  1 14 16]
 [ 1  2 19 16 13 18]
 [ 1 16 19 16 14  4]
 [ 3  9  4 10  8 17]
 [ 8 17  6  2  7  5]]


Median of Array: 

9.5


## Question:11

### Find the transpose of the previous array in Q8?

In [24]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(arr8))

Original Array: 

[[16 13  1  1 14 16]
 [ 1  2 19 16 13 18]
 [ 1 16 19 16 14  4]
 [ 3  9  4 10  8 17]
 [ 8 17  6  2  7  5]]


Transpose of Array: 

[[16  1  1  3  8]
 [13  2 16  9 17]
 [ 1 19 19  4  6]
 [ 1 16 16 10  2]
 [14 13 14  8  7]
 [16 18  4 17  5]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [25]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print("Sum of diagonal elements of Array: \n")
print(np.trace(arr7))

Original Array: 

[[11  9 16 14]
 [19  1 18 10]
 [15  8  9  2]
 [16  3  7 14]]


Sum of diagonal elements of Array: 

35


## Question:13

### Find the determinant of the previous array in Q12?

In [26]:
print("Original Array: \n")
print (arr7)
print("\n")
print("Determinant of Array: \n")
print(np.linalg.det(arr7))

Original Array: 

[[11  9 16 14]
 [19  1 18 10]
 [15  8  9  2]
 [16  3  7 14]]


Determinant of Array: 

25380.000000000004


## Question:14

### Find the 5th and 95th percentile of an array?

In [27]:
print("Original Array: \n")
print (arr7)
print("\n")
print(f"5th percentile of array: {np.percentile(arr7, 5)}")
print(f"95th percentile of array: {np.percentile(arr7, 95)}")

Original Array: 

[[11  9 16 14]
 [19  1 18 10]
 [15  8  9  2]
 [16  3  7 14]]


5th percentile of array: 1.75
95th percentile of array: 18.25


## Question:15

### How to find if a given array has any null values?

In [ ]:
np.isnan(arr7).any()