# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x= np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New folder (9)\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/New folder (9)\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New folder (9)\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/New folder (9)\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New folder (9)\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/New folder (9)\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New folder (9)\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/New folder (9)\\Library\\include']
None


7. Print the dimension of the array in question 3


In [10]:
x.ndim

1

8. Create a boolean array with all the True values

In [6]:
np.ones(10,dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [13]:
x=np.random.randn(2,2)
x

array([[ 1.02317943, -1.09744061],
       [-0.09845132, -0.86820981]])

10. Create a three dimensional array



In [12]:
x=np.random.randn(3,3)
x

array([[-0.65668411,  0.27528404, -0.07351238],
       [ 0.19930424, -1.94454911,  0.75933261],
       [-1.18746265, -0.07200891,  0.35911282]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [14]:

x=np.array([1,2,3,4,5])
print(x)
x[::-1]

[1 2 3 4 5]


array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [16]:

x=np.zeros(10)
x[-1]=1
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

13. Create a 3x3 identity matrix

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [7]:

arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [9]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [10]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
new=arr1==arr2
new

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [11]:
x=np.arange(0,10)
x=x[x % 2 == 1]
x

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [12]:
x[::]=-1
x

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [13]:
arr = np.arange(10)
print(arr)
arr[5:9]=12
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [14]:
x=np.ones((4,4))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [15]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d.ndim
arr2d [arr2d >= 5] = 55
arr2d

array([[ 1,  2,  3],
       [ 4, 55, 55],
       [55, 55, 55]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [16]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0:1]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [17]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x=x.reshape(2,-1)
print(x)
x[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [18]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x=x.reshape(2,-1)
print(x)
x[1][1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [19]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x=x.reshape(2,-1)
print(x)
x[:,3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([3, 8])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
randnums= np.random.randint(1,500, size=(10,10))
print(f"min value is {randnums.min()}")
print(f"min value is {randnums.max()}")

min value is 1
min value is 496


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [22]:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [26]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)


print(names)  
print(data)
print(names == 'Will')
data[names == 'Will']

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.36758395  0.50252905 -1.2081712   1.02123992]
 [ 1.40228535  0.92208146  2.6047127   0.88132138]
 [ 0.43290167 -0.58523232 -1.14918739  0.12642966]
 [-2.21382278  0.01745212 -1.41454715 -0.44093419]
 [ 0.52399258  1.41587643  0.68029622  0.82508441]
 [ 3.72245309  0.32431361  0.38966909 -0.51737434]
 [ 0.05136568 -0.38383552 -1.22569783 -0.33416922]]
[False False  True False  True False False]


array([[ 0.43290167, -0.58523232, -1.14918739,  0.12642966],
       [ 0.52399258,  1.41587643,  0.68029622,  0.82508441]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])   
 data = np.random.randn(7, 4)
 print(names)  
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.74578272 -0.14301638  1.28323229  0.9391748 ]
 [ 0.34165791  1.55174644  0.81494162  0.27161719]
 [ 0.08233593 -0.07387349  0.67039386  2.02850278]
 [-0.79773484  2.32392739 -0.67698077 -0.17945553]
 [-0.80876738 -1.90421817 -0.94813661 -1.08568672]
 [-0.48006666  1.17262736 -0.37841759  0.45606971]
 [ 2.68725979  0.04535465  1.16201709 -0.32562867]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [23]:
arr = np.arange(1,16)
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [24]:

arr = np.arange(1,17)
x=arr.reshape(2,2,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [31]:
x.ndim
x.transpose()

array([-1.54045233e+00, -1.34904322e+00, -1.05707934e+00,  1.33423834e+00,
       -2.31819706e+00,  5.98343998e-01,  6.17281918e-01, -1.13303174e+00,
       -4.09095011e-01, -1.27137965e+00, -1.34026661e+00, -1.11360092e-03,
       -1.89930364e-01, -1.75966787e-01,  6.62975896e-01,  1.06796357e+00,
        6.82488901e-01,  2.13175011e-01,  6.40957228e-01, -4.60260711e-01])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [25]:

x=np.arange(10)
x=np.sqrt(x)
x[x<.5]=0
x

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [26]:
a=np.random.rand(12)
b=np.random.rand(12)
print(a)
print(b)

x=[]
for i in [a,b]:
    x=i.max()
print(x)

[0.32037629 0.20791908 0.66214259 0.19238368 0.06135751 0.07763333
 0.5258248  0.09169893 0.0897318  0.12068509 0.99683841 0.27213675]
[0.84833621 0.36076075 0.0294293  0.60585698 0.66864397 0.45362048
 0.5256805  0.75142909 0.66226223 0.60155492 0.63774537 0.47643415]
0.8483362132957512


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x=np.unique(names)
x=np.sort(x)
x

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [28]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [29]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 


sampleArray=np.delete(sampleArray, 1)
sampleArray

array([34, 73, 82, 22, 12, 53, 94, 66])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [30]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [23]:

x=np.random.randn(20)
x


array([-1.54045233e+00, -1.34904322e+00, -1.05707934e+00,  1.33423834e+00,
       -2.31819706e+00,  5.98343998e-01,  6.17281918e-01, -1.13303174e+00,
       -4.09095011e-01, -1.27137965e+00, -1.34026661e+00, -1.11360092e-03,
       -1.89930364e-01, -1.75966787e-01,  6.62975896e-01,  1.06796357e+00,
        6.82488901e-01,  2.13175011e-01,  6.40957228e-01, -4.60260711e-01])

In [24]:
np.cumsum(x)

array([-1.54045233, -2.88949554, -3.94657488, -2.61233654, -4.93053359,
       -4.3321896 , -3.71490768, -4.84793942, -5.25703443, -6.52841408,
       -7.86868069, -7.86979429, -8.05972465, -8.23569144, -7.57271555,
       -6.50475198, -5.82226308, -5.60908806, -4.96813084, -5.42839155])